<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php"); ?>
<? $APPLICATION->SetPageProperty("title", "Каталог"); ?>
    <!--project start here-->
    <div class="project">
        <?$APPLICATION->IncludeComponent(
            "bitrix:catalog",
            "tender",
            Array(
                "TEMPLATE_THEME" => "red",
                "IBLOCK_TYPE" => "catalog",
                "IBLOCK_ID" => "10",
                "HIDE_NOT_AVAILABLE" => "N",
                "BASKET_URL" => "/personal/cart/",
                "ACTION_VARIABLE" => "action",
                "PRODUCT_ID_VARIABLE" => "id",
                "SECTION_ID_VARIABLE" => "SECTION_ID",
                "PRODUCT_QUANTITY_VARIABLE" => "quantity",
                "ADD_PROPERTIES_TO_BASKET" => "Y",
                "PRODUCT_PROPS_VARIABLE" => "prop",
                "PARTIAL_PRODUCT_PROPERTIES" => "Y",
                "COMMON_SHOW_CLOSE_POPUP" => "N",
                "SEF_MODE" => "Y",
                "SEF_FOLDER" => "/catalog/",
                "AJAX_MODE" => "N",
                "AJAX_OPTION_ADDITIONAL" => "",
                "AJAX_OPTION_JUMP" => "N",
                "AJAX_OPTION_STYLE" => "Y",
                "AJAX_OPTION_HISTORY" => "N",
                "CACHE_TYPE" => "N",
                "CACHE_TIME" => "36000000",
                "CACHE_FILTER" => "N",
                "CACHE_GROUPS" => "Y",
                "USE_MAIN_ELEMENT_SECTION" => "Y",
                "SET_LAST_MODIFIED" => "N",
                "SET_TITLE" => "Y",
                "ADD_SECTIONS_CHAIN" => "Y",
                "ADD_ELEMENT_CHAIN" => "N",
                "USE_ELEMENT_COUNTER" => "Y",
                "USE_SALE_BESTSELLERS" => "Y",
                "USE_FILTER" => "Y",
                "FILTER_NAME" => "",
                "FILTER_FIELD_CODE" => array(
                    0 => "",
                    1 => "",
                ),
                "FILTER_HIDE_ON_MOBILE" => "Y",
                "FILTER_PROPERTY_CODE" => array(
                    0 => "",
                    1 => "",
                ),
                "FILTER_PRICE_CODE" => array(
                    0 => "BASE",
                ),
                "FILTER_OFFERS_FIELD_CODE" => array(
                    0 => "PREVIEW_PICTURE",
                    1 => "DETAIL_PICTURE",
                    2 => "",
                ),
                "FILTER_OFFERS_PROPERTY_CODE" => array(
                    0 => "",
                    1 => "",
                ),
                "USE_COMMON_SETTINGS_BASKET_POPUP" => "N",
                "TOP_ADD_TO_BASKET_ACTION" => "ADD",
                "SECTION_ADD_TO_BASKET_ACTION" => "ADD",
                "DETAIL_ADD_TO_BASKET_ACTION" => array("ADD"),
                "DETAIL_SHOW_BASIS_PRICE" => "Y",
                "FILTER_VIEW_MODE" => "VERTICAL",
                "USE_REVIEW" => "N",
                "USE_COMPARE" => "N",
                "PRICE_CODE" => array("BASE"),
                "USE_PRICE_COUNT" => "Y",
                "SHOW_PRICE_COUNT" => "0",
                "PRICE_VAT_INCLUDE" => "N",
                "PRICE_VAT_SHOW_VALUE" => "N",
                "PRODUCT_PROPERTIES" => array(
                ),
                "USE_PRODUCT_QUANTITY" => "Y",
                "CONVERT_CURRENCY" => "Y",
                "CURRENCY_ID" => "RUB",
                "OFFERS_CART_PROPERTIES" => array(
                    0 => "COLOR_REF",
                    1 => "SIZES_SHOES",
                    2 => "SIZES_CLOTHES",
                ),
                "SHOW_TOP_ELEMENTS" => "N",
                "SECTION_COUNT_ELEMENTS" => "N",
                "SECTION_TOP_DEPTH" => "1",
                "SECTIONS_VIEW_MODE" => "TEXT",
                "SECTIONS_SHOW_PARENT_NAME" => "Y",
                "PAGE_ELEMENT_COUNT" => "15",
                "LINE_ELEMENT_COUNT" => "3",
                "ELEMENT_SORT_FIELD" => "sort",
                "ELEMENT_SORT_ORDER" => "asc",
                "ELEMENT_SORT_FIELD2" => "id",
                "ELEMENT_SORT_ORDER2" => "desc",
                "LIST_PROPERTY_CODE" => array("PICTURE_URL"),
                "INCLUDE_SUBSECTIONS" => "N",
                "LIST_META_KEYWORDS" => "UF_KEYWORDS",
                "LIST_META_DESCRIPTION" => "UF_META_DESCRIPTION",
                "LIST_BROWSER_TITLE" => "UF_BROWSER_TITLE",
                "LIST_OFFERS_FIELD_CODE" => array(
                    0 => "NAME",
                    1 => "PREVIEW_PICTURE",
                    2 => "DETAIL_PICTURE",
                    3 => "",
                ),
                "LIST_OFFERS_PROPERTY_CODE" => array("PICTURE_URL"),
                "LIST_OFFERS_LIMIT" => "0",
                "SECTION_BACKGROUND_IMAGE" => "-",
                "DETAIL_DETAIL_PICTURE_MODE" => "IMG",
                "DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
                "DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
                "DETAIL_PROPERTY_CODE" => array(
                    0 => "PICTURE_URL",
                    1 => "TYPE",
                    2 => "MODEL",
                    3 => "COLOR",
                    4 => "POWER",
                    5 => "MAX_ROOM_AREA",
                ),
                "DETAIL_META_KEYWORDS" => "KEYWORDS",
                "DETAIL_META_DESCRIPTION" => "META_DESCRIPTION",
                "DETAIL_BROWSER_TITLE" => "TITLE",
                "DETAIL_SET_CANONICAL_URL" => "N",
                "DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
                "SHOW_DEACTIVATED" => "N",
                "DETAIL_OFFERS_FIELD_CODE" => array(
                    0 => "NAME",
                    1 => "",
                ),
                "DETAIL_OFFERS_PROPERTY_CODE" => array(
                    0 => "PICTURE_URL",
                    1 => "TYPE",
                    2 => "MODEL",
                    3 => "COLOR",
                    4 => "POWER",
                    5 => "MAX_ROOM_AREA",
                ),
                "DETAIL_BACKGROUND_IMAGE" => "-",
                "DETAIL_STRICT_SECTION_CHECK" => "Y",

                "LINK_IBLOCK_TYPE" => "",
                "LINK_IBLOCK_ID" => "",
                "LINK_PROPERTY_SID" => "",
                "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
                "USE_ALSO_BUY" => "N",
                "DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
                "DISABLE_INIT_JS_IN_COMPONENT" => "N",
                "USE_GIFTS_DETAIL" => "N",
                "USE_GIFTS_MAIN_PR_SECTION_LIST" => "N",
                "USE_GIFTS_SECTION" => "N",
                "USE_STORE" => "Y",
                "STORES" => array("1"),
                "USE_MIN_AMOUNT" => "N",
                "USER_FIELDS" => array(""),
                "FIELDS" => array("ADDRESS", "PHONE"),
                "SHOW_EMPTY_STORE" => "Y",
                "SHOW_GENERAL_STORE_INFORMATION" => "N",
                "STORE_PATH" => "/store/#store_id#",
                "MAIN_TITLE" => "Наличие на складах",
                "USE_BIG_DATA" => "N",
                "OFFERS_SORT_FIELD" => "sort",
                "OFFERS_SORT_ORDER" => "asc",
                "OFFERS_SORT_FIELD2" => "id",
                "OFFERS_SORT_ORDER2" => "desc",
                "PAGER_TEMPLATE" => "arrows",
                "DISPLAY_TOP_PAGER" => "N",
                "DISPLAY_BOTTOM_PAGER" => "Y",
                "PAGER_TITLE" => "Товары",
                "PAGER_SHOW_ALWAYS" => "N",
                "PAGER_DESC_NUMBERING" => "N",
                "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
                "PAGER_SHOW_ALL" => "N",
                "PAGER_BASE_LINK_ENABLE" => "Y",
                "PAGER_BASE_LINK" => "",
                "PAGER_PARAMS_NAME" => "arrPager",
                "SET_STATUS_404" => "N",
                "SHOW_404" => "N",
                "MESSAGE_404" => "",
                "ADD_PICT_PROP" => "-",
                "LABEL_PROP" => "NEWPRODUCT",
                "PRODUCT_DISPLAY_MODE" => "Y",
                "OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
                "OFFER_TREE_PROPS" => array(
                    0 => "COLOR_REF",
                    1 => "SIZES_SHOES",
                    2 => "SIZES_CLOTHES",
                    3 => "",
                ),
                "DETAIL_DISPLAY_NAME" => "Y",
                "DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
                "SHOW_DISCOUNT_PERCENT" => "Y",
                "SHOW_OLD_PRICE" => "Y",
                "DETAIL_SHOW_MAX_QUANTITY" => "N",
                "MESS_BTN_BUY" => "Купить",
                "MESS_BTN_ADD_TO_BASKET" => "В корзину",
                "MESS_BTN_DETAIL" => "Подробнее",
                "MESS_NOT_AVAILABLE" => "Нет в наличии",
                "TOP_VIEW_MODE" => "SECTION",
                "DETAIL_USE_VOTE_RATING" => "Y",
                "DETAIL_VOTE_DISPLAY_AS_RATING" => "rating",
                "DETAIL_USE_COMMENTS" => "N",
                "DETAIL_BLOG_USE" => "Y",
                "DETAIL_VK_USE" => "N",
                "DETAIL_FB_USE" => "Y",
                "DETAIL_FB_APP_ID" => "",
                "DETAIL_BRAND_USE" => "N",
                "SIDEBAR_SECTION_SHOW" => "Y",
                "SIDEBAR_DETAIL_SHOW" => "N",
                "SIDEBAR_PATH" => "/examples/index_inc.php",
                "AJAX_OPTION_ADDITIONAL" => "",
                "SEF_URL_TEMPLATES" => array(
                    "sections" => "",
                    "section" => "#SECTION_CODE#/",
                    "element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
                    "compare" => "compare/",
                )
            ),
            false
        );?>
    </div>
    </div>
    <!--project end here-->


<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>